INSERT INTO `exclusion_lists` (`id`, `prefix`, `accr`, `description`, `import_url`, `is_auto_import`, `is_active`) VALUES
(1, 'oig',  'Federal OIG',  'Office of the Inspector General',  NULL, 0,  0),
(2, 'nyomig', 'NY OMIG',  'New York Office of the Medical Inspector General', 'http://www.omig.ny.gov/data/gensplistns.php', 1,  0),
(3, 'njcdr',  'NJ DCR', 'New Jersey Division of Civil Rights',  'http://www.state.nj.us/treasury/treasfiles/debarment/Debarment.txt', 0,  0),
(4, 'pa1',  'PA Medicheck', 'Pennslyvania Department of Public Welfare',  'http://services.dpw.state.pa.us/dhs/medicheck.txt', 0,  0),
(5, 'oh1',  'OH Medicaid',  'Ohio Department of Job and Family Services', 'http://medicaid.ohio.gov/Portals/0/Providers/Enrollment%20and%20Support/ExclusionSuspensionList.xlsx', 0,  0),
(6, 'il1',  'IL OIG', 'Illinois Department of human Services, Office of the Inspector General', 'http://www.illinois.gov/hfs/oig/Documents/ILMedicaidSanctionsExcel20160421.xls', 0,  0),
(7, 'ky1',  'KY CHFS',  'Kentucky Cabinet for Health and Family Services', 'http://chfs.ky.gov/NR/rdonlyres/99A6E4D1-4EE9-437D-98F4-0FB4369C7100/0/CopyofKYMedicaidTerminationListApril2016web.xls', 0,  0),
(8, 'ma1',  'MA HHS', 'Massachusetts Health and Human Services',  'http://www.mass.gov/eohhs/docs/masshealth/provlibrary/suspended-excluded-masshealth-providers.xls', 0,  0),
(9, 'sc1',  'SC HHS', 'South Carolina Department Health and Human Services',  'https://www.scdhhs.gov/sites/default/files/Exclusion%20Provider%20List%20for%20DHHS%20Website_19.xls', 0,  0),
(10,  'tx1',  'TX OIG', 'Texas Office of the Inspector General',  NULL, 0,  0),
(11,  'sam',  'SAM.gov',  'System for Award Management',  NULL, 0,  0),
(12,  'ct1',  'CT DSS', 'Connecticut Department of Social Services',  'http://www.ct.gov/dss/cwp/view.asp?a=2349&q=310706', 0,  0),
(13,  'ar1',  'AR DHS', 'Arkansas Department of human Services',  'https://ardhs.sharepointsite.net/ExcludedProvidersList/Excluded%20Provider%20List.html', 0,  0),
(14,  'fl2',  'FL AHCA',  'Florida Agency for Health Care Administration',  NULL, 0,  0),
(15,  'mi1',  'MI MDCH',  'Michigan Department of Community Health',  'http://www.michigan.gov/documents/mdch/MI_Sanctioned_Provider_List_375503_7.xls', 0,  0),
(16,  'al1',  'AL Medicaid Agency', 'Alabam Medicaid Agency', 'http://medicaid.alabama.gov/documents/7.0_Fraud_Abuse/7.7_Suspended_Providers/7.7_Provider_Sanction_List_4-5-16.xls', 0,  0),
(17,  'wv2',  'WV MMS', 'West Virginia Medicaid Program', 'https://www.wvmmis.com/WV%20Medicaid%20Provider%20SanctionedExclusion/WV%20Medicaid%20Exclusions%20-%20March%20Posting.pdf,https://www.wvmmis.com/WV%20Medicaid%20Provider%20SanctionedExclusion/WV%20Medicaid%20Provider%20Term%20-%20Exclusion%20Info%20Other%20-%20March%202016%20Posting.pdf,https://www.wvmmis.com/WV%20Medicaid%20Provider%20SanctionedExclusion/WV%20Medicaid%20Terminations%20-%20March%202016%20Posting.pdf', 0,  0),
(18,  'md1',  'MD DHMH',  'Maryland Department of Health &amp; Mental Hygiene', 'http://dhmh.maryland.gov/oig/Documents/04_28_16_Exclusion_Update.xls', 0,  0),
(19,  'id1',  'ID DHW', 'Idaho Department of Health &amp; Welfare', 'http://healthandwelfare.idaho.gov/Portals/0/Providers/Medicaid/ProviderExclusionList.pdf', 0,  0),
(20,  'ne1',  'NE DHHS',  'Nebrask Department of Health &amp; Humna Services',  'http://dhhs.ne.gov/medicaid/Documents/Excluded-Providers.pdf', 0,  0),
(21,  'wy1',  'WY DOH', 'Wyoming Department of health', 'http://www.health.wyo.gov/Media.aspx?mediaId=18376', 0,  0),
(22,  'nv1',  'NV DHHS',  'Nevada Department of Health &amp; Humna Services', 'http://dhcfp.nv.gov/uploadedFiles/dhcfpnvgov/content/Providers/PI/NevadaProviderExclusions.pdf', 0,  0),
(23,  'ca1',  'CA Medi-Cal',  'California Department of Health Care Services, Medi-cal',  'https://files.medi-cal.ca.gov/pubsdoco/Publications/masters-MTP/zOnlineOnly/susp100-49_z03/suspall_032016.xls', 0,  0),
(24,  'hi1',  'Quest Hawaii', 'Department of Human Services Med Quest Division',  'http://www.med-quest.us/PDFs/Providers/MedProvExcl-ReinList.xls', 0,  0),
(25,  'az1',  'AZ AHCCCS',  'Arizona Office of the Inspector General',  'https://web.archive.org/web/20150609233844/http://www.azahcccs.gov/OIG/ExludedProviders.aspx', 0,  0),
(26,  'tn1',  'TennCare', 'Tennesee State Medicaid Program',  'http://www.tn.gov/assets/entities/tenncare/attachments/terminatedproviderlist.pdf', 0,  0),
(27,  'mn1',  'Minnesota MHCP', 'Minnesota Department of Human Resources',  'http://www.dhs.state.mn.us/main/idcplg?IdcService=GET_FILE&RevisionSelectionMethod=LatestReleased&Rendition=Primary&allowInterrupt=1&noSaveAs=1&dDocName=dhs16_177447,http://www.dhs.state.mn.us/main/idcplg?IdcService=GET_FILE&RevisionSelectionMethod=LatestReleased&Rendition=Primary&allowInterrupt=1&noSaveAs=1&dDocName=dhs16_177448', 0,  0),
(28,  'os1',  'OFAC SDN', 'Specially Designated Nationals', NULL, 0,  0),
(29,  'ak1',  'AK DHSS',  'Alaska Department of Health and Social Services',  'http://dhss.alaska.gov/Commissioner/Documents/PDF/AlaskaExcludedProviderList.pdf', 0,  0),
(30,  'ms1',  'MS DOM', 'Mississppi Division of Medicaid',  'https://medicaid.ms.gov/wp-content/uploads/2015/12/SanctionedProvidersList.xlsx', 0,  0),
(31,  'nc1',  'NC DMA', 'North Carolina Division of Medical Assistance',  'https://ncdma.s3.amazonaws.com/s3fs-public/documents/files/State_Excluded_Provider_List_2016_01_27.xlsx,http://www2.ncdhhs.gov/dma/ProgramIntegrity/ProviderExclusionList_082615.xlsx', 0,  0),
(32,  'mo1',  'MMAC', 'Missouri Department of Social Services', 'http://www.mmac.mo.gov/files/Sanction-List-jan-2016.xls', 0,  0),
(33,  'wa1',  'WS HCA', 'Washington State Health Care Authority', 'http://www.hca.wa.gov/medicaid/provider/documents/termination_exclusion.pdf', 0,  0),
(34,  'ks1',  'KS DHE', 'Kansas Department of Health and Environment',  'http://www.kdheks.gov/hcf/medicaid_program_integrity/download/Termination_List.pdf', 0,  0),
(35,  'la1',  'LA DHH', 'Louisiana Department of Health & Hospitals', 'https://adverseactions.dhh.la.gov/SelSearch/GetCsv', 0,  0),
(36,  'nd1',  'ND DHS', 'ND Dept of Human Services',  'http://www.nd.gov/dhs/services/medicalserv/medicaid/docs/pro-exclusion-list.xlsx', 0,  0),
(37,  'mt1',  'Montana DPHHS',  'Montana Department of Public Health and Human services', 'https://dphhs.mt.gov/MontanaHealthcarePrograms/TerminatedExcludedProviders.aspx', 0,  0),
(38,  'dc1',  'DC OCP', 'DC Office of Contracting and Procurement', 'http://ocp.dc.gov/page/excluded-parties-list', 0,  0),
(39,  'ia1',  'IA DHS', 'Iowa Department of Human Services',  'https://dhs.iowa.gov/sites/default/files/2016-04-30%2C%20PI%20term-suspend-probation.zip', 0,  0),
(40,  'ga1',  'GA DCH', 'Georgia Department of Community Health', 'https://dch.georgia.gov/sites/dch.georgia.gov/files/Georgia-DCH-OIG-Medicaid-Exclusions-03102016.xlsx', 0,  0),
(41,  'me1',  'ME DHHS',  'Maine Department of Health and Human Services',  'https://mainecare.maine.gov/PrvExclRpt/April%202016/PI0008-PM_Monthly_Exclusion_Report%20(csv).csv', 0,  0),
(42,  'fdac', 'FDA CI', 'FDA Clinical Investigators', 'http://www.accessdata.fda.gov/scripts/SDA/sdExportData.cfm?sd=clinicalinvestigatorsdisqualificationproceedings&exportType=msexcel', 0,  0),
(43,  'phs',  'NHH PHS',  'NHH PHS',  'http://ori.hhs.gov/ORI_PHS_alert.html', 0,  0),
(44,  'usdocdp',  'UDoC DP',  'US Department of Commerce, Bureau of Industry and Security, Denied Persons', 'http://www.bis.doc.gov/dpl/dpl.txt', 0,  0),
(45,  'fdadl',  'FDA DL', 'FDA Debarment List (Drug Product Applications)', 'http://www.fda.gov/ICECI/EnforcementActions/FDADebarmentList/ucm2005408.htm', 0,  0),
(46,  'cus_spectrum_debar', 'CUS SD', 'Custom Debar List',  NULL, 0,  0),
(47,  'usdosd', 'US Dos DL',  'US Department of State Debar List',  'https://www.pmddtc.state.gov/compliance/documents/debar.xlsx', 0,  0),
(48,  'unsancindividuals',  'UN Sanc Individuals',  'UN Sanctions Individuals List',  'https://www.un.org/sc/suborg/sites/www.un.org.sc.suborg/files/consolidated.xml', 0,  0),
(49,  'unsancentities', 'UN Sanc Entities', 'UN Sanctions Entities List', 'https://www.un.org/sc/suborg/sites/www.un.org.sc.suborg/files/consolidated.xml', 0,  0),
(50,  'healthmil',  'Health Mil', 'Military Health System', 'http://www.health.mil/Military-Health-Topics/Access-Cost-Quality-and-Safety/Quality-And-Safety-of-Healthcare/Program-Integrity/Sanctioned-Providers', 0,  0),
(51,  'csl', 'Consolidated Screening List', 'Consolidated Screening List', 'https://api.trade.gov/consolidated_screening_list/search.csv?api_key=OHZYuksFHSFao8jDXTkfiypO', 0,0);
