INSERT INTO `exclusion_lists` (`id`, `prefix`, `accr`, `description`, `import_url`, `is_auto_import`, `is_active`) VALUES
(1, 'oig',  'Federal OIG',  'Office of the Inspector General',  NULL, 0,  0),
(2, 'nyomig', 'NY OMIG',  'New York Office of the Medical Inspector General', NULL, 1,  0),
(3, 'njcdr',  'NJ DCR', 'New Jersey Division of Civil Rights',  NULL, 0,  0),
(4, 'pa1',  'PA Medicheck', 'Pennslyvania Department of Public Welfare',  NULL, 0,  0),
(5, 'oh1',  'OH Medicaid',  'Ohio Department of Job and Family Services', NULL, 0,  0),
(6, 'il1',  'IL OIG', 'Illinois Department of human Services, Office of the Inspector General', NULL, 0,  0),
(7, 'ky1',  'KY CHFS',  'Kentucky Cabinet for Health and Family Services',  NULL, 0,  0),
(8, 'ma1',  'MA HHS', 'Massachusetts Health and Human Services',  NULL, 0,  0),
(9, 'sc1',  'SC HHS', 'South Carolina Department Health and Human Services',  NULL, 0,  0),
(10,  'tx1',  'TX OIG', 'Texas Office of the Inspector General',  NULL, 0,  0),
(11,  'sam',  'SAM.gov',  'System for Award Management',  NULL, 0,  0),
(12,  'ct1',  'CT DSS', 'Connecticut Department of Social Services',  NULL, 0,  0),
(13,  'ar1',  'AR DHS', 'Arkansas Department of human Services',  NULL, 0,  0),
(14,  'fl2',  'FL AHCA',  'Florida Agency for Health Care Administration',  NULL, 0,  0),
(15,  'mi1',  'MI MDCH',  'Michigan Department of Community Health',  NULL, 0,  0),
(16,  'al1',  'AL Medicaid Agency', 'Alabam Medicaid Agency', NULL, 0,  0),
(17,  'wv2',  'WV MMS', 'West Virginia Medicaid Program', NULL, 0,  0),
(18,  'md1',  'MD DHMH',  'Maryland Department of Health &amp; Mental Hygiene', NULL, 0,  0),
(19,  'id1',  'ID DHW', 'Idaho Department of Health &amp; Welfare', NULL, 0,  0),
(20,  'ne1',  'NE DHHS',  'Nebrask Department of Health &amp; Humna Services',  NULL, 0,  0),
(21,  'wy1',  'WY DOH', 'Wyoming Department of health', NULL, 0,  0),
(22,  'nv1',  'NV DHHS',  'Nevada Department of Health &amp; Humna Services', NULL, 0,  0),
(23,  'ca1',  'CA Medi-Cal',  'California Department of Health Care Services, Medi-cal',  NULL, 0,  0),
(24,  'hi1',  'Quest Hawaii', 'Department of Human Services Med Quest Division',  NULL, 0,  0),
(25,  'az1',  'AZ AHCCCS',  'Arizona Office of the Inspector General',  NULL, 0,  0),
(26,  'tn1',  'TennCare', 'Tennesee State Medicaid Program',  NULL, 0,  0),
(27,  'mn1',  'Minnesota MHCP', 'Minnesota Department of Human Resources',  NULL, 0,  0),
(28,  'os1',  'OFAC SDN', 'Specially Designated Nationals', NULL, 0,  0),
(29,  'ak1',  'AK DHSS',  'Alaska Department of Health and Social Services',  NULL, 0,  0),
(30,  'ms1',  'MS DOM', 'Mississppi Division of Medicaid',  NULL, 0,  0),
(31,  'nc1',  'NC DMA', 'North Carolina Division of Medical Assistance',  NULL, 0,  0),
(32,  'mo1',  'MMAC', 'Missouri Department of Social Services', NULL, 0,  0),
(33,  'wa1',  'WS HCA', 'Washington State Health Care Authority', NULL, 0,  0),
(34,  'ks1',  'KS DHE', 'Kansas Department of Health and Environment',  NULL, 0,  0),
(35,  'la1',  'LA DHH', 'Louisiana Department of Health & Hospitals', NULL, 0,  0),
(36,  'nd1',  'ND DHS', 'ND Dept of Human Services',  NULL, 0,  0),
(37,  'mt1',  'Montana DPHHS',  'Montana Department of Public Health and Human services', NULL, 0,  0),
(38,  'dc1',  'DC OCP', 'DC Office of Contracting and Procurement', NULL, 0,  0),
(39,  'ia1',  'IA DHS', 'Iowa Department of Human Services',  NULL, 0,  0),
(40,  'ga1',  'GA DCH', 'Georgia Department of Community Health', NULL, 0,  0),
(41,  'me1',  'ME DHHS',  'Maine Department of Health and Human Services',  NULL, 0,  0),
(42,  'fdac', 'FDA CI', 'FDA Clinical Investigators', NULL, 0,  0),
(43,  'phs',  'NHH PHS',  'NHH PHS',  NULL, 0,  0),
(44,  'usdocdp',  'UDoC DP',  'US Department of Commerce, Bureau of Industry and Security, Denied Persons', NULL, 0,  0),
(45,  'fdadl',  'FDA DL', 'FDA Debarment List (Drug Product Applications)', NULL, 0,  0),
(46,  'cus_spectrum_debar', 'CUS SD', 'Custom Debar List',  NULL, 0,  0),
(47,  'usdosd', 'US Dos DL',  'US Department of State Debar List',  'https://www.pmddtc.state.gov/compliance/documents/debar.xlsx', 0,  0),
(48,  'unsancindividuals',  'UN Sanc Individuals',  'UN Sanctions Individuals List',  'https://www.un.org/sc/suborg/sites/www.un.org.sc.suborg/files/consolidated.xml', 0,  0),
(49,  'unsancentities', 'UN Sanc Entities', 'UN Sanctions Entities List', 'https://www.un.org/sc/suborg/sites/www.un.org.sc.suborg/files/consolidated.xml', 0,  0),
(50,  'healthmil',  'Health Mil', 'Military Health System', '', 0,  0),
(51,  'csl', 'Consolidated Screening List', 'Consolidated Screening List', 'https://api.trade.gov/consolidated_screening_list/search.csv?api_key=OHZYuksFHSFao8jDXTkfiypO', 0,0);
