name             'sv-client'
maintainer       'SV Developers'
maintainer_email 'SVDevelopers@streamlineverify.com'
description      'Installs and configures the cdm app with all dependencies'
version          '0.1.0'

depends          'codeception'
depends          'composer'
depends          'curl'
depends          'git'
depends          'init'
depends          'liquibase'
depends          'mysql'
depends          'nginx'
depends          'npm'
depends          'php'
depends          'xdebug'
